name: Readme
on:
  workflow_dispatch: {}
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: |
          npm ci
          npm start
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
